### ISSUE TITLE
Update build documentation

### ISSUE THREAD

**Issue by saracope** [chrisjm/openbrewerydb-website#3]
The instructions to run locally indicate:
"The server will be running at http://localhost:4000"

What actually happens: The server fires up on port 3000:
<img width="403" alt="screen shot 2018-10-01 at 7 26 18 pm" src="https://user-images.githubusercontent.com/2197515/46321220-18746f80-c5b0-11e8-876a-5aa32d7dcc66.png">

Need to update the readme doc to indicate the correct port.

**Comment by chrisjm** [comment]
I apologize. I was excited about getting contributions to the repository that I didn't actually look into the issue before giving it a 👍 

Port 4000 is the intended port. I arbitrarily set up my front-end to run at port 4000 and the [back-end](https://github.com/chrisjm/openbrewerydb-api-server) to run at 3000. I set this up via `.env` rather than default. 

Going to push a merge suggestion to #6 to set the default port instead.

Thanks for spotting this!
